build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 0.5

config:
  validation: false
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    allowedConditions: 4
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 24
  LargeClass:
    active: true
    allowedLines: 450
  LongMethod:
    active: true
    allowedLines: 220
  LongParameterList:
    active: true
    allowedFunctionParameters: 10
    allowedConstructorParameters: 10
  NestedBlockDepth:
    active: true
    allowedDepth: 4
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 24
    allowedFunctionsPerClass: 20
    allowedFunctionsPerInterface: 20
    allowedFunctionsPerObject: 24
    allowedFunctionsPerEnum: 12

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  RedundantSuspendModifier:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  TooGenericExceptionCaught:
    active: false
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: true

formatting:
  active: false
  android: true
  autoCorrect: true
  ChainWrapping:
    active: true
    autoCorrect: true
  CommentSpacing:
    active: true
    autoCorrect: true
  Filename:
    active: true
  FinalNewline:
    active: true
    autoCorrect: true
  ArgumentListWrapping:
    active: false
  ImportOrdering:
    active: false
  Indentation:
    active: false
  MaximumLineLength:
    active: false
    maxLineLength: 120
  MultiLineIfElse:
    active: false
  ModifierOrdering:
    active: true
    autoCorrect: true
  NoBlankLineBeforeRbrace:
    active: false
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoEmptyFirstLineInMethodBlock:
    active: false
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnitReturn:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  PackageName:
    active: true
    autoCorrect: true
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  StringTemplate:
    active: true
    autoCorrect: true
  Wrapping:
    active: false

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
  FunctionNaming:
    active: false
    functionPattern: '([a-z][a-zA-Z0-9]*)|([A-Z][A-Za-z0-9]*)|(`.*`)'
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
  MatchingDeclarationName:
    active: false
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'

performance:
  active: true
  ForEachOnRange:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  UnreachableCode:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  active: true
  EqualsNullCall:
    active: true
  LoopWithTooManyJumpStatements:
    active: false
    maxJumpCount: 3
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
    maxLineLength: 120
  MayBeConst:
    active: false
  MayBeConstant:
    active: false
  FunctionExpressionBody:
    active: false
  ModifierOrder:
    active: true
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  ReturnCount:
    active: false
    max: 4
  SafeCast:
    active: true
  ThrowsCount:
    active: true
    max: 3
  UnusedPrivateClass:
    active: true
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  FunctionOnlyReturningConstant:
    active: false
  UseCheckOrError:
    active: false
